const defaultTheme = require("tailwindcss/defaultTheme")

module.exports = {
  content: ["../**/*.liquid", "./src/**/*.jsx"],
  theme: {
    extend: {
      colors: {
        "base-bg1": "rgb(var(--color-base-background-1))",
        "base-bg2": "rgb(var(--color-base-background-2))",
        "base-text": "rgb(var(--color-base-text))",
        accent1: "rgb(var(--color-base-accent-1))",
        accent2: "rgb(var(--color-base-accent-2))",
        "button-label": "rgb(var(--color-base-solid-button-labels))",
        "grayish-blue": "#D2D6DE",
        "light-gray": "#D2D2D2",
        "link-gray": "#929292",
        "pale-gray": "#F6F6F6",
        "athens-gray": "#E9EBEF",
        "v-beige": "#E9D7AE",
        "v-black": "#434343",
        "v-blue": "#455FEF",
        "v-brown": "#76571D",
        "v-clear": "#FAFCFF",
        "v-gold": "#E4C862",
        "v-gray": "#B9B9B9",
        "v-green": "#6B8441",
        "v-iceblue": "#D3E7FF",
        "v-indigo": "#26428B",
        "v-khaki": "#B98E3B",
        "v-mint": "#7FC9BD",
        "v-mocha": "#6B5358",
        "v-navy": "#344571",
        "v-orange": "#EA913F",
        "v-pink": "#F18FDC",
        "v-purple": "#B353E0",
        "v-red": "#e04010",
        "v-white": "#F0F0F0",
        "v-wine": "#9B3C4E",
        "v-yellow": "#F4F862",
      },
      brightness: {
        25: ".25",
      },
      spacing: {
        "dt-v": "32px",
        "dt-h": "10px",
        "mb-v": "32px",
        "mb-h": "20px",
        "grid-dt-v": "var(--grid-dt-v-spacing)",
        "grid-dt-h": "var(--grid-dt-h-spacing)",
        "grid-mb-v": "var(--grid-mb-v-spacing)",
        "grid-mb-h": "var(--grid-mb-h-spacing)",
        "section-my": "50px",
        "1%": "1%",
        "1/10": "10%",
        "2/10": "20%",
        "9/10": "90%",
        "2px": "2px",
        "6px": "6px",
        "8px": "8px",
        "12px": "12px",
        "14px": "14px",
        "16px": "16px",
        "20px": "20px",
        "24px": "24px",
        "32px": "32px",
        "36px": "36px",
        "40px": "40px",
        "42px": "42px",
        "48px": "48px",
        "56px": "56px",
        "64px": "64px",
        "72px": "72px",
        "86px": "86px",
        "96px": "96px",
        "112px": "112px",
        "120px": "120px",
        "7.5vw": "7.5vw",
      },
      padding: {
        "1/10": "10%",
        "8px": "8px",
        "24px": "24px",
        "32px": "32px",
        "44px": "44px",
        "64px": "64px",
      },
      width: {
        "page-content": "var(--page-width)",
        "page-mobile": "90%",
        "70%": "70%",
        "7/10": "70%",
      },
      maxWidth: {
        "modal-content": "var(--modal-content-width)",
      },
      height: {
        "20vh": "20vh",
        "35vh": "35vh",
        "40vh": "40vh",
        "60vh": "60vh",
        "70vh": "70vh",
        "80vh": "80vh",
      },
      maxHeight: {
        "40vh": "40vh",
        "80vh": "80vh",
      },
      lineHeight: {
        "extra-loose": "2.5",
      },
      zIndex: {
        1: "1",
        header: "1000",
        overlay: "2000",
        sidepanel: "2100",
        modal: "2100",
        "modal-cover": "2110",
        "modal-cover-20": "2120",
        "modal-cover-30": "2130",
        "modal-close": "2200",
      },
      inset: {
        "1/10": "10%",
        "2/10": "20%",
      },
    },
    screens: {
      ...defaultTheme.screens,
    },
    fontFamily: {
      body: "var(--font-body-family)",
      heading: "var(--font-heading-family)",
    },
    fontWeight: {
      body: "var(--font-body-weight)",
      "body-bold": "var(--font-body-weight-bold)",
      heading: "var(--font-heading-weight)",
    },
    fontSize: {
      "v-h0": "calc(var(--font-heading-scale) * 4.6rem)",
      "v-h1": "calc(var(--font-heading-scale) * 4.0rem)",
      "v-h2": "calc(var(--font-heading-scale) * 3.6rem)",
      "v-h3": "calc(var(--font-heading-scale) * 2.7rem)",
      "v-h4": "calc(var(--font-heading-scale) * 2.0rem)",
      "v-h5": "calc(var(--font-heading-scale) * 1.5rem)",
      "v-h6": "calc(var(--font-heading-scale) * 1.4rem)",
      "v-h0-s": "calc(var(--font-heading-scale) * 3.4rem)",
      "v-h1-s": "calc(var(--font-heading-scale) * 3.0rem)",
      "v-h2-s": "calc(var(--font-heading-scale) * 2.6rem)",
      "v-h3-s": "calc(var(--font-heading-scale) * 2.0rem)",
      "v-h4-s": "calc(var(--font-heading-scale) * 1.8rem)",
      "v-h5-s": "calc(var(--font-heading-scale) * 1.6rem)",
      "v-h6-s": "calc(var(--font-heading-scale) * 1.4rem)",
      9: "0.9rem",
      10: "1.0rem",
      11: "1.1rem",
      12: "1.2rem",
      13: "1.3rem",
      14: "1.4rem",
      15: "1.5rem",
      16: "1.6rem",
      18: "1.8rem",
      20: "2.0rem",
      22: "2.2rem",
      24: "2.4rem",
      26: "2.6rem",
      28: "2.8rem",
      32: "3.2rem",
      36: "3.6rem",
      40: "4.0rem",
      48: "4.8rem",
      52: "5.2rem",
      56: "5.6rem",
      60: "6.0rem",
      80: "8.0rem",
      100: "10.0rem",
      110: "11.0rem",
      120: "12.0rem",
      150: "15.0rem",
    },
  },
  plugins: [],
}
